*******************************
***  MASTER DO-FILE			***   
***  Dataset: Hgen				***
*******************************
set more off
clear

global  thisyearlist 	"1984 1985 1986 1987 1988 1989 1990 1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018" // list with all years until current year
global	aufwuchs	0		// set this global to 1 if this year, there is an Aufwuchssample, else to 0
global	deen 		"_de"	// set this global to _de or _en to create the german or english dataset, respctively

* 1. Globals for work in do-Files
****************************************************************************************************
global 	thisyear:		di substr("$thisyearlist", length("$thisyearlist")-1, length("$thisyearlist")) 	// number with abbreviated current year
global 	lastyear		"`=$thisyear -1'" 																// number with abbreviated last year
if "${deen}" =="_de" global DEEN "\DE"
if "${deen}" =="_en" global DEEN "\EN"
global  thiswave    "`=$thisyear -8'"
global 	lastyear	"`=$thisyear -1'"
global 	lastwave	"`=$thiswave -1'"

global lastyearlist "09 10 11"
global lastwavelist "z ba bb"
	foreach yr of num 11/$lastyear {
	global lastyearlist $lastyearlist `yr'
	global lastwavelist $lastwavelist is`yr'
	}
global yearlist $lastyearlist $thisyear
global wavelist $lastwavelist is$thisyear
global finaldata = "\\hume\DATA2\SOEP-IS\SOEP-IS 2018 Generierung HiWi\Data\finaldata"
****************************************************************************************************

* 2. Create needed Folders
****************************************************************************************************
*cap mkdir "$..."
*cap mkdir "$..."
****************************************************************************************************

* 3. Create needed Paths as globals
****************************************************************************************************
qui do H:\git\isdatadoku\pathways.do
global  dofilepath		"H:/git/isdatadoku/" //Path of dofiles
****************************************************************************************************

***4. Load Ados:
****************************************************************************************************
*** 4.1 Other Ados
capture which adolist
if _rc==111{ 
	ssc install adolist
}
quietly adolist list
local allAdos `r(names)'
foreach package in fre labutil2 {
	if !regexm("`r(names)'", " `package' ") {
		display as result "Paket " as error  "`package'" as result " wird versucht über SSC-Server zu installieren"
		ssc install `package'
	} 
} 	
*** 4.2 Own functions
*do "FUN_Generierung_WIKI.do"
****************************************************************************************************

* 5. do-Files for generation
****************************************************************************************************
do  "H:\git\isdatadoku\hgen\00_preparation.do"
do  "H:\git\isdatadoku\hgen\01_h_gen_cnstyr.do"
do  "H:\git\isdatadoku\hgen\02_h_gen_moveyr.do"
do 	"H:\git\isdatadoku\hgen\03_h_gen_owner.do"
do 	"H:\git\isdatadoku\hgen\04_h_gen_size.do"
do 	"H:\git\isdatadoku\hgen\05_h_gen_util.do" //zu viele [-1] 2013?
do 	"H:\git\isdatadoku\hgen\06_h_gen_rent.do"
do 	"H:\git\isdatadoku\hgen\07_h_gen_norent.do"
do 	"H:\git\isdatadoku\hgen\08_h_gen_hmonth.do"
do 	"H:\git\isdatadoku\hgen\09_h_gen_hmode.do"
do 	"H:\git\isdatadoku\hgen\10_h_gen_hinc.do"
do  "H:\git\isdatadoku\hgen\11_h_gen_ahinc.do"
do 	"H:\git\isdatadoku\hgen\12_h_gen_nuts1.do"
***************** ab hier ready, wenn ppfad fertig ist********************* 
do  "H:\git\isdatadoku\hgen\13_h_gen_typhh_preparation.do" // muss angepasst werden vorm ausfuehren!
do  "H:\git\isdatadoku\hgen\14_h_gen_typhh_labeling.do" // muss angepasst werden vorm ausfuehren!
do  "H:\git\isdatadoku\hgen\15_h_gen_typhh_problemfaelle.do" // muss angepasst werden vorm ausfuehren!
do  "H:\git\isdatadoku\hgen\16_save_data.do" // muss angepasst werden vorm ausfuehren!
** not sure if the datasets generated by the following dofiles are still used. Look it, up, if not, delete them here and in folder!!
*do  "H:\git\isdatadoku\hgen\18_checkobrelevant_h_gen_hgnrpers.do"

* 6. Delete unnecessary datasets
****************************************************************************************************
*cap erase "..."












